### ISSUE TITLE
Translate workflow

### ISSUE THREAD

**Issue by madbence** [iojs/iojs-hu#5]
Ok, here are my ideas:
1. create issue here (like #2)
2. someone assigns himself
3. create pr with draft, in markdown, we can review the translation here, comment, etc.
4. post can be published on medium (or on some other channel, idk)

ps: I think the lang here should be english, I mean we all do speak english, since we are translating, and everyone (non-hungarian speakers too) can follow our progress.

Feedback @tamascsaba @bling5630 ? If you have ideas, we can try them out, and choose that works best for us.

**Comment by tamascsaba** [comment]
I think is completely acceptable :)

**Comment by bling5630** [comment]
let's do it:)

On 23 February 2015 at 11:57, Tamás Csaba notifications@github.com wrote:

> I think is completely completely :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/iojs/iojs-hu/issues/5#issuecomment-75522714.

## 

_Tamas Puski_

_Journeyman Ninja - Chünin_ @ IseeQ http://www.iseeq.hu/en

_Cell & Viber_: +36.30.533.0873| _Skype_: tamas5630 | LinkedIn
http://www.linkedin.com/pub/tam%C3%A1s-p%C3%BCski/31/386/656 |TPuski
https://twitter.com/TPuski|
